import React from 'react';

export default {
	Kernel: () => [
		<span>/////////////////////////////BEGIN TRANSMISSION/////////////////////////////<br /><br /></span>,
		<span>///////////////////////////LOAD UP ERROR RECIEVED///////////////////////////<br /><br /></span>,
		<span>*<br /></span>,
		<span>(34wpCD error recieved)<br /></span>,
		<span>//</span>,
		<span>.....<br /></span>,
		<span>LOADING WINDOWS XP SERVICE PACK 4 >>>>><br /><br /></span>,
		<span>kernel 4.5.2 \"SUPER SPACE\"<br /></span>,
		<span>busting shell ghost<br /></span>,
		<span>popping kernals<br /><br /></span>,
		<span>...<br /></span>,
		<span>WINDOWS XP SERVICE PACK 4 BOOTUP COMPLETE::<br /><br /></span>,
		<span>forced wakeup pushed from 25.223.196.168:asgard<br /><br /></span>,
		<span>//////////////begin cryostasis wake up//////////////<br /><br /></span>,
		<span>initializing heart pump </span>,
		<span>... </span>,
		<span>done!<br /></span>,
		<span>inflating lung[0] </span>,
		<span>... </span>,
		<span>done!<br /></span>,
		<span>inflating lung[1] </span>,
		<span>... </span>,
		<span>done!<br /></span>,
		<span>initializing brain spark </span>,
		<span>... </span>,
		<span>failed!<br /></span>,
		<span>&#160;&#160;&#160;&#160;&#160;initializing brain spark </span>,
		<span>... </span>,
		<span>done!<br /><br /></span>,
		<span>ping central nervous system<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>...<br />&#160;&#160;&#160;&#160;&#160;timeout 100% packet loss<br /><br /></span>,
		<span>//////////////check ship status//////////////<br /><br /></span>,
		<span>touch NS.bridge:<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>status- 404 bridge not found<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>non-functional<br /><br /></span>,
		<span>touch NS.hull:<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>status- totally gnasty<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>non-functional<br /><br /></span>,
		<span>touch NS.mess:<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>status- lil dirty<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>functional<br /><br /></span>,
		<span>touch NS.core:<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>status- spewing radiation<br />&#160;&#160;&#160;&#160;&#160;</span>,
		<span>subnominal<br /><br /></span>,
		<span>//////////////Ship check complete//////////////<br /><br /></span>,
		<span>//////////////cryostasis wakeup complete//////////////<br /><br /></span>,
		<span>initializing email client</span>,
		<span>... <br /></span>,
	],

	Opening: () => [
		<span>A Blessed Boys production:<br /></span>,
		<br />,
		<br />,
		<span>   _____ ____  ___   ____________   _    ________ __ _____   ________<br /></span>,
		<span>  / ___// __ \/   | / ____/ ____/  | |  / /  _/ //_//  _/ | / / ____/<br /></span>,
		<span>  \__ \/ /_/ / /| |/ /   / __/     | | / // // . /  / //  |/ / / __  <br /></span>,
		<span> ___/ / ____/ ___ / /___/ /___     | |/ // // /| |_/ // /|  / /_/ /  <br /></span>,
		<span>/____/_/   /_/  |_\____/_____/     |___/___/_/ |_/___/_/ |_/\____/   <br /></span>,
		<br />,
		<br />,
		<span>Press Enter to Continue.</span>,
	],

	EmailSent: () => [
		<br />,		
		<span>Sending..........<br /></span>,
		<span>Sent!<br /></span>,
	],

	NameEmail: () => [
		<span className="red">*** ALERT ***<br /></span>,
		<span className="red">New E-mail Recieved!<br /></span>,
		<span>From: odin@valhalla.no<br /></span>,
		<span>Subject: Hello Warrior<br /></span>,
		<br />,
		<span>Hello Warrior.<br /></span>,
		<span>I am <span className="red">Odin</span>, The All-Father.<br /></span>,
		<br />,
		<span>You have been in cryostasis since the <span className="blue">Information Age</span>. It is the year <span className="blue">20XX PA (Post-Armageddon)</span>, and you are drifting aboard the <span className="cyan">NS Fjord VValkyrie</span>. Your vessel and crew have succumb to a <span className="yellow">terrible fate</span>.<br /></span>,
		<br />,
		<span>Your crew was returning home from a raid on <span className="green">Neo-Dublin</span> when an unexpected nuclear fish-salting accident occurred and the main core overheated and caused a great explosion.<br /></span>,
		<br />,
		<span>Every member of your crew was either mutated or killed in the explosion and are now roaming the halls of this vessel, and may prove <span className="red">dangerous</span>.<br /></span>,
		<br />,
		<span>What would you like me to <span className="yellow">call</span> you, Warrior?<br /></span>,
		<br />,
		<span><span className="green">*** DRAFTING ***</span><br /></span>,
		<span>To: odin@valhalla.no<br /></span>,
		<span>Subject: Re: Hello Warrior<br /></span>,
		<br />,
	],
	
	TitleEmail: (name) => [
		<span className="red">*** ALERT ***<br /></span>,
		<span className="red">New E-mail Recieved!<br /></span>,
		<span>From: odin@valhalla.no<br /></span>,
		<span>Subject: Re:Re: Hello Warrior<br /></span>,
		<br />,
		<span>{name}. An interesting name indeed. What is your <span className="yellow">title</span>?<br /></span>,
		<br />,
		<span><span className="green">*** DRAFTING ***</span><br /></span>,
		<span>To: odin@valhalla.no<br /></span>,
		<span>Subject: Re:Re:Re: Hello Warrior<br /></span>,
		<br />,
	],

	BeforeMapEmail: (name, profession) => [
		<span className="red">*** ALERT ***<br /></span>,
		<span className="red">New E-mail Recieved!<br /></span>,
		<span>From: odin@valhalla.no<br /></span>,
		<span>Subject: Re:Re:Re:Re: Hello Warrior<br /></span>,
		<br />,
		<span>Ah, <span className="yellow">{name}</span> the <span className="yellow">{profession}</span>. Yes, I remember you.<br /></span>,
		<br />,
		<span>I call upon you now <span className="yellow">{name}</span>, to go and rid this universe of your mutating vessel.<br /></span>,
		<br />,
		<span>You must reach the core and destroy it for good and finish this.<br /></span>,
		<br />,
		<span>Here on the wall is a map of the <span className="cyan">NSFVV</span>, I have marked your position with a pre-age symbol: *<br /></span>,
		<br />,
	],

	MidMapEmail: () => [
		<br />,
		<span>This map will not be available to you after you leave this room, you will have to mark each room after you've visited them.<br /></span>,
		<span>This is what your map will normally look like:<br /></span>,
		<br />,
	],

	AfterMapEmail: (name, profession) => [
		<br />,
		<span>And here take <span className="blue">these</span>, you may find them useful on your quest.<br /></span>,
		<br />,
		<span className="red">Odin has bestowed upon thee, Soedekilling. <br/>A lyn-gladius that is given to novice warriors.<br/></span>,
		<span className="red">Odin has also bestowed upon thee a <span className="cyan">Palm Pilot</span>, a relic from the <span className="blue">Information Age</span>. You can use this to update your map as you venture further.<br /></span>,
		<br />,
		<span>Now careful, although your Palm Pilot will not affect you, anything you pick up on your journey will slow you down, and ruin your effectiveness in battle.<br /></span>,
		<span>Finally, remember that your keen <span className="yellow">{profession}</span> instinct allows you to seek for \help at any time.<br /></span>,
		<br />,
		<span>Now Go Warrior. You will die in the process, but in doing so you will save the universe.<br /></span>
	],
};
