import Room from '../Map/Room';
import Items from './Items';
import Enemies from './Enemies.js';

function randomMemberOf<T>(array:Array<T>):T {
	return array[Math.floor(Math.random()*array.length)];
}

export default [
	[
		new Room(false, [Items.keys.rusty], null, 'A small box of maintenance supplies is overturned on the floor.'),
		null,
		new Room(false, [Items.statues.nisk], null, 'The rear of the ship Large windows allow a view of the stars beyond, while massive nuclear thrusters loom to each side.'),
		new Room(false, [], null, 'The rear of the ship Large windows allow a view of the stars beyond, while massive nuclear thrusters loom to each side.'),
		null,
		new Room(true, [], Enemies.boss(), 'The nuclear core is in view. The room is bathed in the green glow of the unshielded core.'),
		null,
		new Room(false, [], null, 'The stern of the ship Large windows allow a view of the stars beyond, while massive nuclear thrusters loom to each side.'),
		new Room(false, [Items.playerWeapons.fiskefrikadeller], null, 'The stern of the ship. Large windows allow a view of the stars beyond, while massive nuclear thrusters loom to each side.'),
		null,
		new Room(false, [Items.keys.light], null, 'A line of keyhooks labeled \'Core Access\' is on the wall, though only one key is hanging on it.'),
	],
	
	[
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls. A severed foot is lodged in between two pipes.'),
		new Room(false, [Items.potion], null, 'A gray metal hallway Core exhaust pipes run along the walls.'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls. It smells of spoiled milk.'),
		new Room(false, [], randomMemberOf(Enemies.hard()), 'A gray metal hallway Core exhaust pipes run along the walls.'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls. A green glow is leaking under the door from the room to the east.'),
		new Room(true, [], null, 'The door to the north has a sign: \'Central Drive Core Chamber\'. A green glow emanates from under the door and reflects around the room.'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls.  A green glow is leaking under the door from the room to the west.'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls.'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls.'),
		new Room(false, [Items.potion], null, 'A gray metal hallway Core exhaust pipes run along the walls. A bloody lyn-saber was snapped in half and left on the floor'),
		new Room(false, [], null, 'A gray metal hallway Core exhaust pipes run along the walls.'),
	],
	
	[
		null,
		null,
		null,
		new Room(false, [], null, 'A narrow maintenance hallway A small porthole on the west wall provides a scenic view of a passing nebula.'),
		null,
		null,
		null,
		new Room(false, [], randomMemberOf(Enemies.hard()), 'A narrow maintenance hallway The walls have been smeared with someone\'s surplus blood.'),
		null,
		null,
		null,
	],
	
	[
		new Room(false, [], randomMemberOf(Enemies.hard()), 'Sleeping Quarters, most of the bunks have been torn to shreds. The trash can was carefully placed upside-down.'),
		new Room(false, [Items.keys.bone], null,'A storage closest, a skull sits on the shelf. \'with love, from mom\' is written across the brow.'),
		null,
		new Room(false, [Items.potion], null, 'A narrow maintenance hallway'),
		new Room(false, [], randomMemberOf(Enemies.tough()), 'The floor is covered in strewn human bones and viscera Horned helmets are piled against the north wall, though most have been broken.'),
		new Room(true, [], null, 'A central maintenance room Doors to the west and east provide access to the engine sector.'),
		new Room(false, [], randomMemberOf(Enemies.tough()), 'This room is spotless Someone even took the time to clean the ceilings.'),
		new Room(false, [Items.potion], null, 'A narrow maintenance hallway'),
		null,
		new Room(true, [Items.statues.caeven], null, 'Capt. Ormskaeg\'s private room The Captain\'s belongings have been thrown onto the floor.'),
		new Room(false, [], randomMemberOf(Enemies.hard()), 'Sleeping quarters, bunks are pushed against the north and east walls.'),
	],
	
	[
		new Room(false, [Items.potion], null, 'Sleeping quarters, the west and east walls are lined with bunks Blood on the floor is evidence of a recent fight.'),
		null,
		new Room(false, [Items.playerWeapons.hestespiser], null, 'A large bathroom, someone knocked over all the stall walls. How rude.'),
		null,
		null,
		new Room(false, [], null, 'A hallway, the door to the north has a sign on it: \'Engine Sector Access\'.'),
		null,
		null,
		new Room(false, [Items.keys.iron], null, 'A small alcove filled with shelves The shelves are mostly filled with salted fish.'),
		null,
		new Room(false, [], null, 'These were sleeping quarters, though all the beds seem to be missing.'),
	],
	
	[
		new Room(false, [], randomMemberOf(Enemies.medium()), 'Sleeping quarters, the bunks are orderly and well made.'),
		new Room(false, [], null, 'This is the west sleeping quarter wing, the bunks are all in place but someone tore all the sheets off.'),
		new Room(false, [], randomMemberOf(Enemies.medium()), 'A nice looking room, the shag carpet is an unfortunate shade of orange. Also its full of cockroaches or something.'),
		new Room(false, [], null, 'A wide hallway. The walls are lined with elaborate oil paintings of the captain.'),
		new Room(false, [], null, 'A wide hallway. The sides of the hall are lined with busts of the captain.'),
		new Room(false, [], randomMemberOf(Enemies.medium()), 'The captain\'s prized atrium, the wood panel walls are polished to a shine.'),
		null,
		new Room(false, [], randomMemberOf(Enemies.medium()), 'A dull hallway, the floors are a grey metal and the walls are a sickly shade of green.'),
		new Room(false, [], null, 'A slightly-less-than dull hallway, the floors a slightly-less-than grey metal.'),
		new Room(false, [], null, 'The tacky carpet in this room has been pounded flat by thousands of viking boots.'),
		new Room(false, [Items.potion], null, 'A billiards room, someone smashed all the balls into a fine rainbow dust.'),
	],
	
	[
		null,
		null,
		new Room(false, [], randomMemberOf(Enemies.tough()), 'What looks to be an abandoned living room.  Some of the pillows look like they  have been shredded by some beast..'),
		null,
		null,
		new Room(false, [Items.potion], null, 'Backed into a corner, this dust filled room has nothing of importance.'),
		new Room(false, [], null, 'An open hallway, branching into three different rooms.'),
		new Room(false, [], null, 'Backed into a corner, this dust filled room has nothing of importance.'),
		null,
		null,
		null,
	],
	
	[
		new Room(false, [Items.keys.janitor], null, 'The space janitor was kind enough to leave his door unlocked before perishing, hopefully he left his keys too.'),
		null,
		new Room(true, [], null, 'Backed into a corner, this dust filled room has nothing of importance.'),
		new Room(false, [], null, 'Backed into a corner, this dust filled room has nothing of importance.'),
		null,
		null,
		null,
		new Room(false, [Items.statues.lockhaert], null, 'The room, though very much delapitated like the rest of the ship, bears the sweet, sweet musk of achievement.'),
		null,
		new Room(false, [], randomMemberOf(Enemies.medium()), 'Stepping closer to the center of the room brings the sensation of hundreds of screaming voices gasping their final breaths. Gnarsty.'),
		null,
	],
	
	[
		new Room(false, [], null, 'A maintenance hallway, there are some brooms in here. They probably won\'t make good weapons.'),
		null,
		null,
		new Room(false, [], null, 'This was the combat practice area, unfortunately somebody already took all the weapons.'),
		new Room(false, [Items.playerWeapons.andetaender], null, 'Marksmanship practice took place in here, some old targets hang on the far wall.'),
		new Room(false, [], null, 'Weapons storage for the practice rooms. It looks pretty barren.'),
		new Room(false, [Items.statues.traesk], null, 'This room hasn\'t been opened in years, a box is upended on the floor.'),
		null,
		new Room(false, [Items.keys.bent], null, 'A dusty, forgotton little room. Someone was keeping their collection of loose keys in here, though most of them are pretty bent.'),
		new Room(false, [Items.potion], null, 'A tall, airy chamber. The ceiling has a stained glass cupola. Apparently the captain stole it off some Neo-British station way back.'),
		new Room(false, [Items.playerWeapons.vejmon], null, 'Backed into a corner, this dust filled room has nothing of importance.'),
	],
	
	[
		new Room(false, [], null, 'A maintenance hallway, the space janitor left his tools here in a hurry.'),
		new Room(false, [], randomMemberOf(Enemies.medium()), 'This room is full of card tables. The decks have thrown around the room.'),
		new Room(false, [Items.potion], null, 'A storage room, the walls are lined with metal crates covered in dust (and some blood).'),
		new Room(false, [], randomMemberOf(Enemies.medium()), 'This was the canteen, there doesn\'t seem to be any food left. Maybe under the counter?'),
		null,
		null,
		null,
		null,
		null,
		new Room(false, [], randomMemberOf(Enemies.medium()), 'This hallway is painted in the most hideous shade of turquoise you have ever seen.'),
		null,
	],
	
	[
		null,
		new Room(false, [], null, 'Escape pods line the west wall, all the door handles have been broken off them.'),
		null,
		new Room(false, [], null, 'The mess hall, all the plates are smashed on the floor and rotting food is everywhere.'),
		null,
		new Room(false, [], null, 'There aren\'t any more pods, but there are some awfully bloody controls here. Some intestines too.'),
		new Room(false, [Items.potion], null, 'Even more cyrostatis pods, how many warriors do they have on hold?'),
		new Room(false, [], randomMemberOf(Enemies.easy()), 'More cryostatis pods, this place is full of the things.'),
		null,
		new Room(false, [], null, 'This hallway is completely plain and unremarkable'),
		null,
	],
	
	[
		null,
		new Room(false, [], randomMemberOf(Enemies.easy()), 'The main exterior airlock, this is where the warriors would leave the ship on their raids.'),
		new Room(false, [], null, 'Space-Bearskin spacesuits are hung in long rows through the room.'),
		new Room(false, [Items.playerWeapons.solvarmer], null, 'Oxygen tanks are stacked to the ceiling, a lot of them are empty.'),
		null,
		new Room(false, [], randomMemberOf(Enemies.easy()), 'This is a service hallway, pretty boring really. A lot of metal here, as it happens.'),
		null,
		new Room(false, [], null, 'The cryostatis chamber you woke up in, other warriors from various ages are inanimate in their respective pods.'),
		null,
		new Room(false, [Items.keys.trophy], null, 'The hallway is lined with trophy cases. There are some trophies too. \'Norse Soccer Champions 20XX-4\', huh.'),
		new Room(true, [Items.statues.duenn], null, 'This seems to be a treasure closet. A burlap sack in the corner is labelled \'swag bag\'.'),
	],
	
	[
		null,
		new Room(false, [], null, 'An unremarkable hallway. A sign points north and reads: \'Main Airlock\'.'),
		null,
		null,
		null,
		new Room(false, [], randomMemberOf(Enemies.easy()), 'This is a service hallway, its made of wood for some reason. Elaborate scenes of viking glory are carved into the walls.'),
		null,
		null,
		new Room(false, [Items.potion], null, 'Recreational quarters once upon a time, the room is full of severed heads now.'),
		new Room(false, [], null, 'Recreational quarters, table tennis etc. Looks fun.'),
		null,
	],
	
	[
		null,
		new Room(false, [], randomMemberOf(Enemies.easy()), 'A largely unremarkable hallway. A sign points south and reads: \'Bridge Access and Fish Saltery\'.'),
		null,
		new Room(false, [], randomMemberOf(Enemies.tough()), 'The wall panelling is spread around the room. The pipes have been pulled out of the wall and are spraying superheated steam in the air.'),
		new Room(true, [], null, 'A security room. It was locked down prety tight until you found the key. Someone already emptied the weapon cabinet.'),
		new Room(false, [], null, 'A nice snack room, the vending machines are fully stocked. A bulkhead automatically sealed off access to the west.'),
		new Room(false, [], randomMemberOf(Enemies.easy()), 'The salt storage depository, someone took the time to smash all the salt jars. What a jerk.'),
		new Room(false, [], null, 'A pleasant hallway, rather 1970s with some wood panelling.'),
		new Room(false, [], randomMemberOf(Enemies.easy()), 'Recreational quarters, or they were. More like a morgue now really. Pretty grizzly.'),
		new Room(false, [], null, 'Recreational quarters, the rooms is filled with startlingly uncomfortable looking couches.'),
		new Room(false, [], randomMemberOf(Enemies.easy()), 'A bay window reveals a beautiful space vista. Someone taped a chore list to the window. It\'s Sveinbjorn\'s day to do the dishes, he probably won\'t though.'),
	],
	
	[
		new Room(false, [Items.playerWeapons.bjoernkrammer], null, 'The bow of the ship A large window to the south provides a view of passing asteroids.'),
		new Room(false, [Items.potion], null, 'The bow of the ship The bulkhead to the south has sealed off access to the bridge. The room is full of comfortable chairs and piles of half-salted fish.'),
		new Room(false, [], randomMemberOf(Enemies.easy()), 'The bow of the ship A human skeleton is lounging on a couch in front of the window. The large window provides a nice view of the star the ship is orbiting. Is that the bridge floating over there?.'),
		new Room(false, [], null, 'The bow of the ship Normally one could see the bridge through the southern window, but it seems to be missing.'),
		null,
		new Room(false, [], null, 'The secondary bow airlock is to the west, but it has been automatically sealed.'),
		null,
		new Room(false, [Items.playerWeapons.sjoraeningi], null, 'The main bow airlock is to east, but it has been automatically sealed. Half salted fish litters the floor You can see a distant gas giant through the large window to the south.'),
		null,
		null,
		null,
	],
];